apiVersion: v1
kind: Service
metadata:
  name: shepokes
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: shepokes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shepokes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shepokes
  template:
    metadata:
      labels:
        app: shepokes
    spec:
      containers:
      - name: shepokes-site
        image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        ports:
        - containerPort: 8080
