name: Docker Image CI K8s CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci_jobs:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.Declare_Vars.outputs.TAG }}
      output2: ${{ steps.Declare_Vars.outputs.IMAGE_NAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Declare_Vars
      working-directory: ./app
      run: |
        TAG=$(date +%s)
        IMAGE_NAME=kfface/shepokes-site
        echo $TAG
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$TAG

  cd_jobs:
    needs: ci_jobs  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.3.0
      with: 
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.K8S_CLUSTER_ID }}
    - name: Apply Deployment 1 & 2
      env:
        TAG: ${{ needs.ci_jobs.outputs.output1 }}
        IMAGE_NAME: ${{ needs.ci_jobs.outputs.output2 }}
      working-directory: ./k8s    
      run: |
        echo $TAG
        kubectl apply -f shepokes-depl1.yaml
        kubectl apply -f shepokes-depl2.yaml        
