name: Docker Image CI K8s CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci_jobs:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.declare_vars.outputs.TAG }}
      IMAGE_NAME: ${{ steps.declare_vars.outputs.IMAGE_NAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: set output
      id: declare_vars
      working-directory: ./app
      run: |
        TAG=$(date +%s)
        IMAGE_NAME="kfface/shepokes-site"
        echo "TAG=$TAG" >> $GITHUB_OUTPUT
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
        echo $IMAGE_NAME
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$TAG
  cd_jobs:
    needs: ci_jobs  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.3.0
      with: 
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.K8S_CLUSTER_ID }}
    - name: retrieve output
      run: |
        echo ${{ needs.ci_jobs.outputs.TAG }}
        echo ${{ needs.ci_jobs.outputs.IMAGE_NAME }}
    - name: Apply Deployment 1 & 2
      env:
        TAG: ${{ needs.ci_jobs.outputs.TAG }}
        IMAGE_NAME: ${{ needs.ci_jobs.outputs.IMAGE_NAME }}
      working-directory: ./k8s    
      run: |
        kubectl get pods
        echo $IMAGE_NAME
        export TAG=$TAG
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo $TAG
        kubectl apply -f shepokes-depl1.yaml
        kubectl apply -f shepokes-depl2.yaml
    - name: Debug
      run: |
        echo "TAG: $TAG"
        
