name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./app
      run: |
        TAG=$(date +%s)
        IMAGE_NAME=kfface/shepokes-site
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$TAG
